### ISSUE TITLE
[feat] Blobby demo base64 encoding -> SVG

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/blobstream-starknet#103]
In the `blobby` demo, read the base64 svg encoding given in step 6, then decode and display the SVG like in step 1.

Example base64 SVG encoding : `data:image/svg+xml;base64,CiAgICAgIDxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB2aWV3Qm94PSIwIDAgMTAwIDEwMCI+CiAgICAgICAgPGNpcmNsZSBjeD0iNTAiIGN5PSI1MCIgcj0iNDAiIGZpbGw9IiNhZDExZjciIC8+CiAgICAgICAgPHRleHQgeD0iNTAiIHk9IjUwIiBmb250LXNpemU9IjEyIiBmb250LWZhbWlseT0ic2Fucy1zZXJpZiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZHk9Ii4zZW0iIGZpbGw9IndoaXRlIj5GbG9yaWFuPC90ZXh0PgogICAgICA8L3N2Zz4KICAgIA==`

( Decode the `CiAgICA...` part using base64 )

#### References
Continuation of #42

Blobby: https://github.com/keep-starknet-strange/blobstream-starknet/tree/main/blobby

**Comment by remybar** [comment]
Hi @b-j-roberts !

Can I work on this task ? (and maybe on https://github.com/keep-starknet-strange/blobstream-starknet/issues/102 at the same time as both are strongly linked).
