### ISSUE TITLE
[feat] Allow freezing BlobstreamX

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/blobstream-starknet#110]
Implement the frozen functionality from Succinct's BlobstreamX contract.

#### References

https://github.com/succinctlabs/blobstreamx/blob/a2ca7f434b013eaa3b7bd39dd0a2a405f99eb056/contracts/src/BlobstreamX.sol#L124
https://github.com/succinctlabs/blobstreamx/blob/a2ca7f434b013eaa3b7bd39dd0a2a405f99eb056/contracts/src/BlobstreamX.sol#L72 ( change to get / set pair )

**Comment by thomas192** [comment]
Hey, I'd like to do this one
