### ISSUE TITLE
[dev] Use Alexandria's sol_abi Traits

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/blobstream-starknet#125]
`Alexandria` now has the `sol_abi` library, which provides a similar DevEx to Solidity for bytes encoding/decoding.
It would be helpful to change our `append_X` calls throughout the code to `encode_packed` calls. This would make future development more accessible and maybe provide some insight into the new `sol_abi` traits.

### References

- [Alexandria sol_abi traits](https://github.com/keep-starknet-strange/alexandria/tree/main/src/encoding#solidity-abi)
- [Example location in code to change](https://github.com/keep-starknet-strange/blobstream-starknet/blob/0b9483b14a1e2631624bf6211676bec3542d57ea/src/tree/namespace/hasher.cairo#L10)

**Comment by thomas192** [comment]
Hey, may I take it ?
