### ISSUE TITLE
[feat] DA Verifier

### ISSUE THREAD

**Issue by b-j-roberts** [keep-starknet-strange/blobstream-starknet#127]
Implement and test the `DAVerifier` module from the Blobstream contracts. This is the main module rollups will use to verify DA in their core contracts.

#### References
- [Blobstream DAVerifier](https://github.com/celestiaorg/blobstream-contracts/blob/master/src/lib/verifier/DAVerifier.sol)
- [DAVerifier Tests](https://github.com/celestiaorg/blobstream-contracts/tree/master/src/lib/verifier/test)

**Comment by b-j-roberts** [comment]
I created a draft PR containing my work for implementing the `DAVerifier` module. I'm not sure I'll have time to finish this, so someone else can take this over.

Work that still needs to be done :
- Finish implementing the `test_rollup_inclusion_proofs.cairo`
- Implement `da_verifier.cairo`
- clean up code and any issues existing

**Comment by thomas192** [comment]
Hey, I can work on this
