### ISSUE TITLE
[feat] Sepolia Deployment

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#130]
The idea of this PR is to implement the tooling around blobstream Starknet to easily deploy the contract on Sepolia.

This includes:

1. Compiling the contracts
2. Deploying the contracts configured to interact with the herodotus fact registry, [list of deployments is here](https://docs.herodotus.dev/herodotus-docs/developers/contract-addresses#starknet-sepolia).
3. Documenting this process to be easily repeatable by user.

To achieve this task, several options:

1. Bash script with Starkli
2. Starknet foundry [scripting](https://foundry-rs.github.io/starknet-foundry/starknet/script.html)

**Comment by thomas192** [comment]
May I take this one?
