### ISSUE TITLE
[feat] Data Commitment Script

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#138]
Updating Starknet BlobstreamX data commitments from the Herodotus Fact registry.

**Comment by drspacemn** [comment]
@thomas192 are you free for this per this comment?

https://github.com/keep-starknet-strange/blobstream-starknet/issues/85#issuecomment-2042284643

**Comment by thomas192** [comment]
> @thomas192 are you free for this per this comment?
> 
> https://github.com/keep-starknet-strange/blobstream-starknet/issues/85#issuecomment-2042284643

I am !
