### ISSUE TITLE
[feat] binary hash digest

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#23]
Develop the Binary Merkle Tree Hasher such that it passes the Celestia tests:
https://github.com/keep-starknet-strange/blobstream-starknet/blob/main/src/tree/binary/tests/test_hasher.cairo

#### References
Verify if we need a full implementation of abi.encodePacked or not (some util funcs here: 
https://github.com/keep-starknet-strange/blobstream-starknet/blob/main/src/utils.cairo

Blobstream(sol) https://github.com/celestiaorg/blobstream-contracts/blob/master/src/lib/tree/binary/test/TreeHasher.t.sol

**Comment by Godspower-Eze** [comment]
I can work on this

**Comment by b-j-roberts** [comment]
I was able to get this implemented and working with Celestia's tests.

No new abi encoder implementation was needed. Just using [Alexandria Bytes](https://github.com/keep-starknet-strange/alexandria/tree/main/src/bytes) seems sufficient.
