### ISSUE TITLE
[feat] binary merkle tree

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#24]
Implement and test the Binary Merkle Tree from the Celestia Blobstream contracts. 

#### References
Verify if there is anything reusable from the alexandria merkle tree implementation

Ensure the following tests are implemented and pass:
https://github.com/celestiaorg/blobstream-contracts/blob/master/src/lib/tree/binary/test/BinaryMerkleTree.t.sol

**Comment by robinstraub** [comment]
I'll gladly take this one if u can assign it to me :D
