### ISSUE TITLE
[feat] contract events

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#25]
Implement the Blobstream events in the contract and test their emission:
- `DataRootTupleRootEvent`
- `ValidatorSetUpdatedEvent`

These can include stubs or full implementation of calling contract code.

#### References
https://github.com/celestiaorg/blobstream-contracts/blob/e2b8e53ea6f42a3bbbf2e88c41f038b18adf3c86/src/Blobstream.sol#L66

**Comment by OthmanSefraoui** [comment]
Hey ! I can work on this issue
