### ISSUE TITLE
[feat] contract errors

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#26]
Implement the Blobstream errors in the contract and tests:
- MalformedCurrentValidatorSet
- InvalidSignature
- InsufficientVotingPower
- InvalidValidatorSetNonce
- SuppliedValidatorSetInvalid
- InvalidDataRootTupleRootNonce

These can include stubs or full implementation of calling contract code.

#### References
https://github.com/celestiaorg/blobstream-contracts/blob/e2b8e53ea6f42a3bbbf2e88c41f038b18adf3c86/src/Blobstream.sol#L80

**Comment by JordyRo1** [comment]
Hi, can I work on this issue ?

**Comment by JordyRo1** [comment]
Hey @drspacemn , I published a draft version of blobstream contract, where I handled the errors and the functions that used these errors. I also wrote some tests based on the errors. Do you want me to also test the general function logic too (for example test `update_validator_set` , `submit_data_root_tuple_root` ?
