### ISSUE TITLE
[feat] namespace hash digest

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#27]
Develop the Namespace Merkle Tree Hasher such that it passes the Celestia tests.

#### References
Verify if we need a full implementation of abi.encodePacked or not (some util funcs here: 
https://github.com/keep-starknet-strange/blobstream-starknet/blob/main/src/utils.cairo

(coordinate with #23)

Blobstream(sol) https://github.com/celestiaorg/blobstream-contracts/blob/master/src/lib/tree/namespace/test/TreeHasher.t.sol

**Comment by Darlington02** [comment]
let me take this

**Comment by Darlington02** [comment]
@drspacemn please assign @Godspower-Eze in my stead

**Comment by drspacemn** [comment]
@Godspower-Eze please comment here

**Comment by Godspower-Eze** [comment]
👀👀

**Comment by b-j-roberts** [comment]
@Godspower-Eze I had done this and posted it in the telegram, which might help some with this issue : 

namespace.id is encoded under bytes28 in the Blobstream contract. So you'll need to append the 28 bytes from the bytes31 id.

```
use alexandria_math::U256BitShift;

let mut var256: u256 = namespace.id.into();
var256 = U256BitShift::shl(var256, 8);
let mut bytes28Bytes: Bytes = BytesTrait::new(28, array![var256.high, var256.low]);
encoding.concat(bytes28Bytes);
```

**Comment by Godspower-Eze** [comment]
> @Godspower-Eze I had done this and posted it in the telegram, which might help some with this issue :
> 
> namespace.id is encoded under bytes28 in the Blobstream contract. So you'll need to append the 28 bytes from the bytes31 id. Here is one possible way to do that.
> 
> ```
> use alexandria_math::U256BitShift;
> 
> let mut var256: u256 = namespace.id.into();
> var256 = U256BitShift::shl(var256, 8);
> let mut bytes28Res: Bytes = BytesTrait::new(28, array![var256.high, var256.low]);
> encoding.concat(bytes28Res);
> ```

Nice. Thank you. I would take note of this.

**Comment by Godspower-Eze** [comment]
Based on @Akashneelesh comments on the call, he's already working on this because he needs it for the #30. @Akashneelesh please confirm this.

**Comment by Akashneelesh** [comment]
> Based on @Akashneelesh comments on the call, he's already working on this because he needs it for #30. @Akashneelesh please confirm this.

@b-j-roberts I had used the same function, I'll push a draft pr so that everyone could look at the issue.

**Comment by Akashneelesh** [comment]
I was trying to test out the bytes28 appending part.
So here down below I was using this function where namespace.tobytes() is not used instead directly using the namespace version and id (testing purpose for validation)
```
function leafDigest(Namespace memory namespace, bytes memory data) public pure returns (NamespaceNode memory) {
    bytes32 digest = sha256(abi.encodePacked(LEAF_PREFIX,namespace.version,namespace.id, data));
    NamespaceNode memory node = NamespaceNode(namespace, namespace, digest);
    return node;
}
```
Where the inputs were 
Namespace memory nid = Namespace(0xde, 0xadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefde);
bytes memory data = hex"69";

Cairo :
```
fn append_bytes31(ref self: Bytes, value: bytes31) {
    let mut value_u256: u256 = value.into();
    value_u256 = U256BitShift::shl(value_u256, 8);
    let mut bytes28Bytes: Bytes = BytesTrait::new(28, array![value_u256.high, value_u256.low]);
    self.concat(@bytes28Bytes);
}
```
And after passing these inputs I was getting the digest as 0x3624c7f7169cb5bbd0d010b851ebd0edca10b2a1b126f5fb1a6d5e0d98356e63 in solidity whereas in cairo with the same input using the append_bytes31 function , I was getting the digest as 0xbc1312650c27cc07a20248cd012ae4e7a5f3725ec41f02d390cb269ec7aec08d.

If I remove the namespace.id, from encoding on solidity and cairo, they give the same expected digest. But doesnt work the same while using namespace.id.

cc : @drspacemn , @b-j-roberts and @Godspower-Eze
