### ISSUE TITLE
[feat] Namespace Funcs

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#28]
For type Namespace, impl:
- NamespacePartialOrd
- NamespacePartialEq

Ensure type param `<Namespace>.id` type change to bytes31 is safe, add test to prove.

#### References
https://github.com/celestiaorg/blobstream-contracts/blob/master/src/lib/tree/Types.sol

**Comment by MSghais** [comment]
Can I try this one, please?

**Comment by Akashneelesh** [comment]
> Can I try this one, please?

Hey @MSghais since I had a dependency for it in the namespace merkle_tree and this issue wasnt completed, so I had completed this issue.
