### ISSUE TITLE
[feat] namespace merkle tree

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#30]
Implement and test the Namespace Merkle Tree from the Celestia Blobstream contracts.

References
Verify if there is anything reusable from the alexandria merkle tree implementation

Ensure the following tests are implemented and pass:
https://github.com/celestiaorg/blobstream-contracts/blob/master/src/lib/tree/namespace/test/NamespaceMerkleTree.t.sol

**Comment by Akashneelesh** [comment]
Hey @drspacemn I would like to take this up.

**Comment by b-j-roberts** [comment]
Hey @Akashneelesh , I implemented some of the utils I think you'll need for this work [here](https://github.com/keep-starknet-strange/blobstream-starknet/blob/9364fb0bb179bcb9ab85dd6b6e133c2c5e078ef6/src/tree/utils.cairo).

Going to be merging them into main soon.

**Comment by Akashneelesh** [comment]
Hey @b-j-roberts I have completed the utils for it as well, Im almost done with the namespace merkle tree

**Comment by b-j-roberts** [comment]
Hey @Akashneelesh , are you still working on this? If not, would it be fine to free up the issue for someone else to take over?

**Comment by Akashneelesh** [comment]
> Hey @Akashneelesh , are you still working on this? If not, would it be fine to free up the issue for someone else to take over?

Hello @b-j-roberts yes sure this can be freed up and someone else can be assigned but also in the mean time I'll push the draft pr for this so anyone can continue of from it.

**Comment by thomas192** [comment]
Hello, I'd be happy to pick up where things left off :)

**Comment by Akashneelesh** [comment]
@b-j-roberts I have pushed a Draft PR which contains functions like (next_sub_tree_size,bits_trailing_zeroes,compute_root,pop_leaves_if_non_empty,pop_proof_if_non_empty,pop_if_non_empty,verify,verify_inner and verify_multi) except verify_multi_hashes
