### ISSUE TITLE
[dev] benchmark SN testnet blobs

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#32]
Integrate a script that benchmarks the average cost for Starknet to submit blob data to Ethereum L1 for comparison.

Should display a nice readout of the data.
- Total Blob Size
- Blob Fee
- Blob Gas Used
- Gas if ETH calldata (blobscan calls it `Blob As Calldata Gas`)
- Gas if Celestia blob was [used](https://docs.celestia.org/developers/submit-data#estimating-gas-programmatically)

**Refs**
- https://blobscan.com/blob/0x01394306d3a5e6456771c2a4689e98269d220636723a877e44f19e11f6e57e6d

**Comment by 0xicosahedron** [comment]
i can work on this

**Comment by 0xicosahedron** [comment]
current blockers is finding an API to get ETH blob data and from which address is starknet contract submitting blobs
