### ISSUE TITLE
[feat] Contract Bindings

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#33]
Initialize the contract bindings similar to the original contracts Go bindings.

Tasks:
- evaluate what language to write the bindings in Rust || Go
- communicated it in this ticket and on TG
- implement or start the implementation of the bindings

#### References
- https://github.com/celestiaorg/blobstream-contracts/blob/master/wrappers/Blobstream.sol/wrapper.go

**Comment by okhaimie-dev** [comment]
I can attempt this. @drspacemn

**Comment by drspacemn** [comment]
Happy to chat more about the implementation. Ping the TG if you want to discuss the details.

**Comment by okhaimie-dev** [comment]
@drspacemn can you unassign me from this task. Something came up IRL, and I might not be able to get started for another 3 weeks, I wouldn't want to make this a blocker if someone else wants to take a shot at it.

**Comment by drspacemn** [comment]
Yup, thank you for letting me know. Happy to have you once you're back.

**Comment by JameWade** [comment]
@drspacemn Do you mean to write an starknet abi generator similar to `https://geth.ethereum.org/docs/tools/abigen`?or just do this manually?

**Comment by drspacemn** [comment]
Correct, but we are actually going to put this ticket on hold until we bootstrap the new Blobstream X contracts. @JameWade  are you part of the Telegram?

**Comment by drspacemn** [comment]
Can start the development here, full implementation can be done pending #51 
Please start with binding tooling here:
https://github.com/cartridge-gg/cainome

**Comment by ermvrs** [comment]
I can take that.

**Comment by b-j-roberts** [comment]
Hey @ermvrs , are you still working on this? If not, can I free the task for someone else to take over?

**Comment by thomas192** [comment]
I could work on it if it's free @ermvrs @b-j-roberts :)
