### ISSUE TITLE
[feat] UI Demo

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#42]
Similar UI demo of interacting with the blobstream contracts on Starknet as was developed here

#### References
https://www.based64.xyz

**Comment by faytey** [comment]
I’m interested in this

**Comment by drspacemn** [comment]
FYI:

Since the contracts are not currently built out or deployed. This may involve mostly mocking and setting up Starknet UI libraries for the time being until we have something deployed to testnet.

**Comment by faytey** [comment]
Okay cool, so while waiting and mocking up, can I work on another issue also

**Comment by FlorianLgrs** [comment]
I'm also interested? I can do figma high fidelity mockups and prototype if needed :)

**Comment by drspacemn** [comment]
If you two could coordinate on the work that would be great. Feel free to break the work into smaller issues and I can assign.

**Comment by MSghais** [comment]
Can I contribute also to the Frontend, Smart-contract, or whatever around Blobstream? 
Let me know @drspacemn, please.
I've finish few PR soon, ready for new work!

**Comment by drspacemn** [comment]
@MSghais of course. There are some open tickets for contract/infra dev feel free to claim on.

If you'd like to work specifically on the UI. I think we will have to scope the work a bit more.

**Comment by drspacemn** [comment]
@Faithia7 please initialize the next app in the project root with the name blobby. Can you coordinate the design work with @flo_durden ? 

Feel free to create further issues for the work and I can assign them as needed.

**Comment by faytey** [comment]
The project has been initialized as a nextjs project, @FlorianLgrs can you proceed with the figma and create an issue for it please

**Comment by FlorianLgrs** [comment]
Issue created here : https://github.com/keep-starknet-strange/blobstream-starknet/issues/59
