### ISSUE TITLE
[dev] Scarb 2.5.0

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#49]
bump scarb version to `2.5.0` and handle any breaking changes

**Comment by ametel01** [comment]
happy to take this

**Comment by ametel01** [comment]
This is currently blocked by OZ still on 2.4.4. Workaround could be to temporarily depend on a forked OZ repo until the official one is updated. 
Waiting for corfirmation

**Comment by drspacemn** [comment]
Thank you for the contribution. For the time being let's not work off a fork.

If you see support is added by OZ can you resubmit without the fork?
