### ISSUE TITLE
[dev] Blobstream X Funcs

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#51]
Finish general functions implementation:
- tests
- `commitHeaderRange`
- `requestNextHeader`
- `commitNextHeader`
- `getHeaderHash`

NOTE -> `ISuccinctGateway` can be commented or stubbed for the time being (work done in #73 )
NOTE -> `requestHeaderRange` is being handled by #68 

### Refs
- https://github.com/succinctlabs/blobstreamx/blob/364d3dc8c8dc9fd44b6f9f049cfb18479e56cec4/contracts/src/BlobstreamX.sol#L81

**Comment by drspacemn** [comment]
handled by #47

**Comment by drspacemn** [comment]
Finish general functions implementation (tests + missing functions). Follow up to #47.

@JordyRo1

**Comment by JordyRo1** [comment]
Will work on it

**Comment by JordyRo1** [comment]
Hey @drspacemn the implementation of the given functions is done, but I think I need the SuccintGateway in order to write proper tests. Do I try to test the logic without the SuccintGateway or wait for the issue #73 to be over ?
