### ISSUE TITLE
[feat] UX/UI Design

### ISSUE THREAD

**Issue by FlorianLgrs** [keep-starknet-strange/blobstream-starknet#59]
Create high fidelity mockups similar to based64.xyz using Figma.

Responsive layout based on Tailwind recommandations (5 breakpoints).

**Comment by FlorianLgrs** [comment]
@drspacemn could you assign it to me please ?
Thanks !

**Comment by FlorianLgrs** [comment]
Mockups are ready !

Design has been declined on 3 breakpoints : mobile, tablet and desktop.

On mobile and tablet, I used is a fluid grid : 12 col with 16px gutter and 16px (=1rem) margin on left and right.
On desktop, I used a 1440px grid : 12 col (100px each) with 16px gutter and 32px (=2rem) margin on left and right.

All the design is based on multiples of 4 : margin/padding can be 4, 8, 12, 16, 20, 24, etc.

Link : 
- Mobile : https://www.figma.com/file/ERLVGfpJ0dRzxyZ89tfhOF/Blobstream-Starknet?type=design&node-id=2118%3A59&mode=design&t=MNDMTxxg8w4zZSe4-1
- Tablet : https://www.figma.com/file/ERLVGfpJ0dRzxyZ89tfhOF/Blobstream-Starknet?type=design&node-id=2118%3A60&mode=design&t=MNDMTxxg8w4zZSe4-1
- Desktop : https://www.figma.com/file/ERLVGfpJ0dRzxyZ89tfhOF/Blobstream-Starknet?type=design&node-id=2118%3A62&mode=design&t=MNDMTxxg8w4zZSe4-1

Let me know if you need anything else !

**Comment by drspacemn** [comment]
great work!
