### ISSUE TITLE
[feat] Header Range

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#68]
- add header range feat

NOTE -> `ISuccinctGateway` can be commented or stubbed for the time being (work done in #73 )

#### References
`HeaderRangeRequested`
`requestHeaderRange`

https://github.com/succinctlabs/blobstreamx/blob/364d3dc8c8dc9fd44b6f9f049cfb18479e56cec4/contracts/src/interfaces/IBlobstreamX.sol#L26

https://github.com/succinctlabs/blobstreamx/blob/364d3dc8c8dc9fd44b6f9f049cfb18479e56cec4/contracts/src/BlobstreamX.sol#L100

**Comment by OthmanSefraoui** [comment]
I can work on this !
