### ISSUE TITLE
[feat] NextJS App 

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#75]
Continuation #42 

Next.js application in the project root called `blobby` that implements the application logic for the Figma designs bootstrapped here:

https://github.com/keep-starknet-strange/blobstream-starknet/issues/59#issuecomment-1930800975

**Comment by faytey** [comment]
Hi @drspacemn can i take on this

**Comment by b-j-roberts** [comment]
Just merged @faytey's PR setting up the `blobby` demo's frontend. The following application logic is still needed, from what I understand : 
1. Dynamically generate the SVG base64 encoding from the input on step 1 and output on step 2.
2. Properly decode and display the SVG in step (6) after input is given

**Comment by faytey** [comment]
ok i just worked on the dummy UI, the full integration will be done when some things are available as mentioned by @drspacemn

**Comment by faytey** [comment]
So can i work on another Issue now

**Comment by drspacemn** [comment]
Nice work. Feel free to comment on another ticket you would feel comfortable with

**Comment by drspacemn** [comment]
Nice work. Feel free to comment on another ticket you would feel comfortable with

**Comment by faytey** [comment]
Can you assist with open available issues please, @drspacemn @b-j-roberts

**Comment by drspacemn** [comment]
Ahh good point. Okay will notify you in TG when we open new issues

**Comment by faytey** [comment]
Thanks a lot
