### ISSUE TITLE
[feat] Reentrancy Guard

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/blobstream-starknet#92]
[Reentrancy Guard ](https://github.com/keep-starknet-strange/piltover/issues/2)

**Comment by Akinbola247** [comment]
i'd like to work on this

**Comment by AryanGodara** [comment]
Hi, I'd like to work on this one; I went through the linked issue in the description; but could you please elaborate on this issue a bit please. Which contract(s) do we have to apply the modifier to?
